management:
  endpoints:
    web:
      exposure:
        include: *
    enabled-by-default: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true